### ISSUE TITLE
error during dev-stock startup: Could not connect to debugging client.

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/oc-opencloudmesh#13]
```
executing init.sh on oc1.docker
Xdebug: [Log Files] File '/tmp/xdebug_remote.log' could not be opened.
Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(
```
@mahdibaghbani can this error be safely ignored?

**Comment by MahdiBaghbani** [comment]
Yes it can be safely ignored.

The `Xdebug: [Log Files] File '/tmp/xdebug_remote.log' could not be opened.` is because the permission mismatch, I changed the log file location to `/var/www/html/xdebug.log` in https://github.com/pondersource/dev-stock/commit/6c6b601dee8f7fbe8cc0fd9fc1e007e11016a65f#diff-e6dded5040b9a9a9834ac007aadd6c264dd38f6a81b7c6a0c27c7b39987e2650R6

The `Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(`

happens when you run the container without running a debugger on VSCode, it simply means the debugger client is not running and isn't fatal
