### ISSUE TITLE
delete shared file from the NC side (receiver) does not work.

### ISSUE THREAD

**Issue by navid-shokri** [pondersource/oc-opencloudmesh#29]
When I share a file with a remote group from OC to NC and then I try to delete the shared file from the receiving party (NC) by clicking the `Leave this share`
![image](https://github.com/pondersource/oc-opencloudmesh/assets/123634558/a89c3cd0-8611-4288-b2cb-aba977958841)

the file will disappear but when I refresh the page the share confirmation will be prompted again:

![image](https://github.com/pondersource/oc-opencloudmesh/assets/123634558/0a63e868-104a-4911-9c71-d143307f8c92)

**Comment by thepeak99** [comment]
@michielbdejong we need the PO wisdom here :)

**Comment by michielbdejong** [comment]
OK, so the scenario is written down in a confusing way:
> When I share a file with a remote group from OC to NC

in this half of the sentence, "I" is the sending party

> and then I try to delete the shared file from the receiving party (NC)

in this half of the sentence, "I" seems to be the receiving party

I think this is expected behaviour. If one member of the receiving group wants to reject the share, it should not remove the share for the other group members. I think this is the same behaviour for share to a local group on OC.
